export interface Product {
  id: string;
  slug: string;
  sku: string;
  name: string;
  description: string;
  price: number;
  discountPrice?: number;
  rating: number;
  reviewsCount: number;
  imageUrl: string;
  images: string[];
  stock: number;
  brand: string;
  category: string;
  categorySlug: string;
  specifications: Record<string, string>;
  datasheetUrl?: string;
  tutorialsUrl?: string[];
  compatibility?: string[];
  packageContents?: string[];
  warranty?: string;
  gstPercentage: number;
  isFeatured: boolean;
  skillLevel: "Beginner" | "Intermediate" | "Advanced";
}

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "arduino-uno-r3-development-board",
    sku: "ARD-UNO-R3",
    name: "Arduino Uno R3 ATmega328P Development Board",
    description: "The Arduino Uno R3 is a microcontroller board based on the ATmega328P. It has 14 digital input/output pins, 6 analog inputs, a 16 MHz ceramic resonator, a USB connection, a power jack, an ICSP header, and a reset button. Perfect for beginners and advanced projects alike.",
    price: 899,
    discountPrice: 549,
    rating: 5,
    reviewsCount: 342,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 150,
    brand: "Arduino",
    category: "Development Boards",
    categorySlug: "arduino",
    specifications: {
      "Microcontroller": "ATmega328P",
      "Operating Voltage": "5V",
      "Input Voltage": "7-12V",
      "Digital I/O Pins": "14",
      "Analog Input Pins": "6",
      "Flash Memory": "32 KB",
      "Clock Speed": "16 MHz",
    },
    datasheetUrl: "#",
    tutorialsUrl: ["#"],
    compatibility: ["Arduino IDE", "PlatformIO", "Shields"],
    packageContents: ["Arduino Uno R3 Board", "USB Cable", "Pin Headers"],
    warranty: "6 months",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Beginner",
  },
  {
    id: "2",
    slug: "esp32-devkit-v1-wifi-bluetooth",
    sku: "ESP32-DEVKIT-V1",
    name: "ESP32 DevKit V1 WiFi + Bluetooth Development Board",
    description: "ESP32 is a low-cost, low-power system-on-chip (SoC) with WiFi and dual-mode Bluetooth capabilities. The ESP32 DevKit V1 features a dual-core processor, making it ideal for IoT applications, home automation, and smart sensor networks.",
    price: 599,
    discountPrice: 399,
    rating: 4,
    reviewsCount: 218,
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 230,
    brand: "Espressif",
    category: "IoT Modules",
    categorySlug: "esp32",
    specifications: {
      "Processor": "Dual-core Xtensa LX6",
      "Clock Speed": "Up to 240 MHz",
      "WiFi": "802.11 b/g/n",
      "Bluetooth": "v4.2 BR/EDR + BLE",
      "Flash Memory": "4 MB",
      "GPIO Pins": "36",
      "Operating Voltage": "3.3V",
    },
    datasheetUrl: "#",
    compatibility: ["Arduino IDE", "ESP-IDF", "MicroPython"],
    packageContents: ["ESP32 DevKit V1 Board", "Pin Headers (pre-soldered)"],
    warranty: "6 months",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Intermediate",
  },
  {
    id: "3",
    slug: "raspberry-pi-4-model-b-4gb",
    sku: "RPI4-4GB",
    name: "Raspberry Pi 4 Model B - 4GB RAM",
    description: "The Raspberry Pi 4 Model B is the latest product in the popular Raspberry Pi range of computers. It offers ground-breaking increases in processor speed, multimedia performance, memory, and connectivity compared to the prior-generation Raspberry Pi 3 Model B+.",
    price: 5499,
    discountPrice: 4799,
    rating: 5,
    reviewsCount: 567,
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 45,
    brand: "Raspberry Pi Foundation",
    category: "Development Boards",
    categorySlug: "raspberry-pi",
    specifications: {
      "Processor": "Broadcom BCM2711 Quad-core Cortex-A72",
      "RAM": "4GB LPDDR4-3200",
      "WiFi": "Dual-band 802.11ac",
      "Bluetooth": "5.0 BLE",
      "USB": "2x USB 3.0, 2x USB 2.0",
      "Video Output": "2x micro-HDMI (4Kp60)",
      "GPIO": "40-pin",
    },
    datasheetUrl: "#",
    compatibility: ["Raspberry Pi OS", "Ubuntu", "Windows IoT"],
    packageContents: ["Raspberry Pi 4 Board"],
    warranty: "1 year",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Intermediate",
  },
  {
    id: "4",
    slug: "ultrasonic-sensor-hc-sr04",
    sku: "SEN-HCSR04",
    name: "HC-SR04 Ultrasonic Distance Sensor Module",
    description: "The HC-SR04 ultrasonic sensor module provides 2cm to 400cm non-contact measurement functionality with ranging accuracy that can reach up to 3mm. Perfect for obstacle detection, distance measurement, and robotics projects.",
    price: 99,
    discountPrice: 59,
    rating: 4,
    reviewsCount: 890,
    imageUrl: "https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 500,
    brand: "Generic",
    category: "Sensors",
    categorySlug: "sensors",
    specifications: {
      "Working Voltage": "DC 5V",
      "Working Current": "15mA",
      "Measuring Range": "2cm - 400cm",
      "Measuring Angle": "15°",
      "Trigger Input Signal": "10μS TTL pulse",
      "Output Signal": "Echo TTL pulse",
    },
    packageContents: ["HC-SR04 Module"],
    warranty: "3 months",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Beginner",
  },
  {
    id: "5",
    slug: "universal-robotics-trainer-kit-v01",
    sku: "DSIB-URTK-V01",
    name: "Universal Robotics Trainer Kit V0.1",
    description: "Complete robotics learning platform designed for engineering students and hobbyists. Includes chassis, motors, sensors, Arduino board, and a comprehensive project guide. Build line followers, obstacle avoiders, and Bluetooth-controlled robots.",
    price: 7999,
    discountPrice: 4999,
    rating: 5,
    reviewsCount: 123,
    imageUrl: "https://images.unsplash.com/photo-1553406830-ef2513450d76?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 32,
    brand: "DSIB Tech",
    category: "Robotics Kits",
    categorySlug: "robotics",
    specifications: {
      "Kit Type": "Complete Robotics Trainer",
      "Board": "Arduino Uno Compatible",
      "Motors": "4x BO Motors",
      "Driver": "L298N Motor Driver",
      "Sensors": "IR, Ultrasonic, Bluetooth",
      "Chassis": "Acrylic Multi-layer",
      "Power": "18650 Battery Holder",
    },
    datasheetUrl: "#",
    tutorialsUrl: ["#"],
    compatibility: ["Arduino IDE"],
    packageContents: [
      "Acrylic Chassis",
      "4x BO Motors with Wheels",
      "Arduino Uno R3",
      "L298N Motor Driver",
      "HC-SR04 Ultrasonic Sensor",
      "IR Sensor Pair",
      "HC-05 Bluetooth Module",
      "Jumper Wires Set",
      "Battery Holder",
      "Project Guide Booklet",
    ],
    warranty: "1 year",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Beginner",
  },
  {
    id: "6",
    slug: "servo-motor-sg90-micro",
    sku: "MOT-SG90",
    name: "SG90 Micro Servo Motor 9g",
    description: "The SG90 is a tiny and lightweight servo motor with high output power. It can rotate approximately 180 degrees, works with many microcontrollers, and is perfect for robotics, RC planes, and embedded projects.",
    price: 149,
    discountPrice: 89,
    rating: 4,
    reviewsCount: 1250,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 800,
    brand: "TowerPro",
    category: "Motors",
    categorySlug: "motors",
    specifications: {
      "Weight": "9g",
      "Operating Voltage": "4.8V - 6V",
      "Stall Torque": "1.8 kg/cm",
      "Operating Speed": "0.1s/60°",
      "Rotation": "~180°",
      "Gear Type": "Plastic",
    },
    packageContents: ["SG90 Servo Motor", "3x Servo Horns", "Screws"],
    warranty: "3 months",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Beginner",
  },
  {
    id: "7",
    slug: "oled-display-128x64-i2c-ssd1306",
    sku: "DISP-OLED-128x64",
    name: "0.96\" OLED Display Module 128x64 I2C SSD1306",
    description: "A compact OLED display module with 128x64 pixels, featuring high contrast and wide viewing angle. Uses the SSD1306 driver and communicates over I2C, making it easy to integrate with Arduino, ESP32, and Raspberry Pi projects.",
    price: 249,
    discountPrice: 159,
    rating: 5,
    reviewsCount: 445,
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 340,
    brand: "Generic",
    category: "Displays",
    categorySlug: "displays",
    specifications: {
      "Display Size": "0.96 inch",
      "Resolution": "128x64 pixels",
      "Driver IC": "SSD1306",
      "Interface": "I2C",
      "Operating Voltage": "3.3V - 5V",
      "Color": "Blue / White",
    },
    compatibility: ["Arduino", "ESP32", "Raspberry Pi", "STM32"],
    packageContents: ["OLED Display Module", "Pin Headers"],
    warranty: "3 months",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Beginner",
  },
  {
    id: "8",
    slug: "lm2596-dc-dc-buck-converter",
    sku: "PWR-LM2596",
    name: "LM2596 DC-DC Step Down Buck Converter Module",
    description: "Adjustable output voltage DC-DC buck converter module based on the LM2596 regulator. Efficiently steps down voltage from 3.2V-40V input to 1.25V-35V output, ideal for powering microcontrollers and motors from higher voltage batteries.",
    price: 79,
    discountPrice: 49,
    rating: 4,
    reviewsCount: 670,
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 620,
    brand: "Generic",
    category: "Power Modules",
    categorySlug: "power",
    specifications: {
      "Input Voltage": "3.2V - 40V DC",
      "Output Voltage": "1.25V - 35V DC (Adjustable)",
      "Output Current": "3A (Max)",
      "Efficiency": "Up to 92%",
      "Switching Frequency": "150 KHz",
    },
    packageContents: ["LM2596 Module"],
    warranty: "3 months",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Intermediate",
  },
  {
    id: "9",
    slug: "stem-iot-smart-home-kit",
    sku: "DSIB-STEM-IOT-01",
    name: "STEM IoT Smart Home Learning Kit",
    description: "A comprehensive STEM kit designed for students to learn IoT and smart home concepts. Includes ESP32, relay modules, sensors, LED strips, and a detailed step-by-step guide to build a complete smart home prototype with mobile app control.",
    price: 3999,
    discountPrice: 2999,
    rating: 5,
    reviewsCount: 78,
    imageUrl: "https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 55,
    brand: "DSIB Tech",
    category: "STEM Kits",
    categorySlug: "stem-kits",
    specifications: {
      "Board": "ESP32 DevKit",
      "Modules": "Relay, DHT11, LDR, MQ-2, PIR",
      "Actuators": "LED Strip, Buzzer, Servo",
      "App": "Blynk IoT Compatible",
      "Projects": "8+ Smart Home Projects",
      "Guide": "100+ Page Booklet",
    },
    tutorialsUrl: ["#"],
    packageContents: [
      "ESP32 DevKit",
      "4-Channel Relay Module",
      "DHT11 Temperature Sensor",
      "LDR Sensor Module",
      "MQ-2 Gas Sensor",
      "PIR Motion Sensor",
      "RGB LED Strip (1m)",
      "Buzzer",
      "SG90 Servo",
      "Breadboard",
      "Jumper Wires",
      "Project Guide Booklet",
    ],
    warranty: "1 year",
    gstPercentage: 18,
    isFeatured: true,
    skillLevel: "Beginner",
  },
  {
    id: "10",
    slug: "jumper-wire-kit-120pcs",
    sku: "WIRE-JMP-120",
    name: "Jumper Wire Kit 120pcs (M-M, M-F, F-F)",
    description: "Essential set of 120 premium jumper wires in three configurations: Male-to-Male, Male-to-Female, and Female-to-Female. 20cm length, color-coded for easy identification. A must-have for any prototyping or breadboard project.",
    price: 199,
    discountPrice: 129,
    rating: 4,
    reviewsCount: 1840,
    imageUrl: "https://images.unsplash.com/photo-1553406830-ef2513450d76?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 1200,
    brand: "Generic",
    category: "Connectors",
    categorySlug: "connectors",
    specifications: {
      "Quantity": "120 pieces (40 each type)",
      "Types": "M-M, M-F, F-F",
      "Length": "20cm / 8 inches",
      "Wire Gauge": "24 AWG",
      "Connector": "DuPont",
    },
    packageContents: ["40x Male-Male Wires", "40x Male-Female Wires", "40x Female-Female Wires"],
    warranty: "No warranty",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Beginner",
  },
  {
    id: "11",
    slug: "drone-frame-f450-quadcopter",
    sku: "DRN-F450",
    name: "F450 Quadcopter Drone Frame Kit with Landing Gear",
    description: "Premium F450 quadcopter frame kit with integrated PCB for clean wiring. Includes 4 arms, top and bottom plates, and tall landing gear. Wheelbase 450mm, perfect for building custom drones with standard motor mounts.",
    price: 799,
    discountPrice: 599,
    rating: 4,
    reviewsCount: 156,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 67,
    brand: "DJI Compatible",
    category: "Drones",
    categorySlug: "drones",
    specifications: {
      "Wheelbase": "450mm",
      "Weight": "282g",
      "Material": "PA66 + Glass Fiber",
      "Motor Mount": "Standard 16mm",
      "Max Payload": "~800g",
      "Landing Gear Height": "75mm",
    },
    packageContents: ["Top Plate", "Bottom PCB Plate", "4x Arms", "Landing Gear Set", "Screws Kit"],
    warranty: "No warranty",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Advanced",
  },
  {
    id: "12",
    slug: "ne555-timer-ic-dip8",
    sku: "IC-NE555",
    name: "NE555 Timer IC DIP-8 (Pack of 5)",
    description: "The NE555 is a highly stable controller capable of producing accurate time delays or oscillation. Pack of 5 ICs. Used in timer, pulse generation, and oscillator applications in virtually every electronics lab.",
    price: 49,
    rating: 4,
    reviewsCount: 2100,
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=600&auto=format&fit=crop",
    images: [],
    stock: 3000,
    brand: "Texas Instruments",
    category: "ICs & Semiconductors",
    categorySlug: "ics",
    specifications: {
      "Package": "DIP-8",
      "Supply Voltage": "4.5V - 16V",
      "Output Current": "200mA",
      "Frequency": "Up to 500 KHz",
      "Timing Range": "μs to hours",
    },
    packageContents: ["5x NE555 Timer IC"],
    warranty: "No warranty",
    gstPercentage: 18,
    isFeatured: false,
    skillLevel: "Intermediate",
  },
];

export const categories = [
  { name: "Arduino", slug: "arduino", count: 24 },
  { name: "ESP32 & IoT", slug: "esp32", count: 18 },
  { name: "Raspberry Pi", slug: "raspberry-pi", count: 12 },
  { name: "Sensors", slug: "sensors", count: 45 },
  { name: "Robotics Kits", slug: "robotics", count: 15 },
  { name: "Motors & Drives", slug: "motors", count: 22 },
  { name: "Displays", slug: "displays", count: 14 },
  { name: "Power Modules", slug: "power", count: 19 },
  { name: "STEM Kits", slug: "stem-kits", count: 8 },
  { name: "Drones", slug: "drones", count: 6 },
  { name: "ICs & Semiconductors", slug: "ics", count: 52 },
  { name: "Connectors", slug: "connectors", count: 30 },
];

export const brands = [
  "Arduino",
  "Espressif",
  "Raspberry Pi Foundation",
  "DSIB Tech",
  "TowerPro",
  "Texas Instruments",
  "Generic",
  "DJI Compatible",
];
